import { describe, it, expect, afterAll } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import { createClient } from "@supabase/supabase-js";
import { hasDatabase, withClient, publicEnv } from "./db";

/*
 * AC-009 — new versus existing account, driven against REAL Supabase Auth.
 *
 * "New user sets password before onboarding; existing user signs in and accepts
 * without password reset; neither gains access before acceptance."
 *
 * Nothing here is mocked. The invite link is generated by the Auth admin API
 * and redeemed with its one-time token, which is exactly what following the
 * emailed link does — without needing mail delivery, which is T21's gate.
 *
 * The browser half of this journey is in tests/e2e/invitations.spec.ts.
 */
const fixtures = JSON.parse(readFileSync(path.join(__dirname, "../fixtures.json"), "utf8"));
const ADMIN = fixtures.ids.admin;
const ORG_A = fixtures.ids.org_a;
const DANA = fixtures.ids.dana;

const NEWCOMER = "journey-newcomer@example.invalid";

const service = createClient(publicEnv.projectUrl, publicEnv.serviceRoleKey, {
  auth: { autoRefreshToken: false, persistSession: false },
});
/** A fresh anonymous client, the way a browser would arrive. */
const anonClient = () =>
  createClient(publicEnv.projectUrl, publicEnv.publishableKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

const createdUsers: string[] = [];

/*
 * app.profiles references auth.users with ON DELETE RESTRICT, so the
 * application rows have to go first or the Auth account cannot be removed.
 */
async function removeAccount(id: string) {
  await withClient(async (client) => {
    await client.query("DELETE FROM app.invitations WHERE user_id=$1", [id]);
    await client.query("DELETE FROM app.memberships WHERE user_id=$1", [id]);
    await client.query("DELETE FROM app.profiles WHERE id=$1", [id]);
  }).catch(() => {});
  await service.auth.admin.deleteUser(id).catch(() => {});
}

/*
 * These tests create real Auth accounts, so an earlier interrupted run can
 * leave one behind. Clearing by address first makes the suite repeatable
 * rather than passing only on a clean project.
 */
async function removeByEmail(email: string) {
  for (let page = 1; page <= 10; page += 1) {
    const { data } = await service.auth.admin.listUsers({ page, perPage: 200 });
    if (!data || data.users.length === 0) return;
    const found = data.users.find((u) => (u.email ?? "").toLowerCase() === email);
    if (found) {
      await removeAccount(found.id);
      return;
    }
  }
}

afterAll(async () => {
  for (const id of createdUsers) await removeAccount(id);
  /*
   * This suite commits, unlike the ones that roll back, so it puts the shared
   * learner back the way the seed left her. Otherwise the next run of any
   * suite that expects the seeded state starts from a different database.
   */
  await withClient(async (client) => {
    await client.query("DELETE FROM app.invitations WHERE user_id=$1", [DANA]);
    await client.query("UPDATE app.profiles SET onboarded_at=NULL, display_name='Dana' WHERE id=$1", [DANA]);
    await client.query(
      "UPDATE app.memberships SET status='invited' WHERE user_id=$1 AND organization_id=$2",
      [DANA, ORG_A]
    );
  }).catch(() => {});
});

describe.skipIf(!hasDatabase)("AC-009 a brand new account", () => {
  it("sets a password before it is onboarded, and has no access until it accepts", async () => {
    await removeByEmail(NEWCOMER);

    // 1. The invitation creates an Auth identity with no password of its own.
    const { data: invite, error: inviteError } = await service.auth.admin.generateLink({
      type: "invite",
      email: NEWCOMER,
    });
    expect(inviteError).toBeNull();
    const userId = invite!.user!.id;
    createdUsers.push(userId);

    const password = `journey-${Math.random().toString(36).slice(2)}-Aa1!`;
    const invitationId = "f2000001-0000-4000-8000-000000000000";

    await withClient(async (client) => {
      await client.query(
        `INSERT INTO app.profiles(id,email,display_name) VALUES ($1,$2,'Newcomer')`,
        [userId, NEWCOMER]
      );
      await client.query(
        `INSERT INTO app.memberships(organization_id,user_id,role,status) VALUES ($1,$2,'learner','invited')`,
        [ORG_A, userId]
      );
      await client.query(
        `INSERT INTO app.invitations(id,user_id,organization_id,role,status,expires_at,created_by)
         VALUES ($1,$2,$3,'learner','pending', now() + interval '24 hours', $4)`,
        [invitationId, userId, ORG_A, ADMIN]
      );
    });

    // 2. Before anything else: the account cannot be signed into at all.
    const cannotSignIn = await anonClient().auth.signInWithPassword({
      email: NEWCOMER,
      password,
    });
    expect(cannotSignIn.error).not.toBeNull();

    // 3. Following the emailed link. The one-time token is what the link carries.
    const redeeming = anonClient();
    const { data: session, error: otpError } = await redeeming.auth.verifyOtp({
      email: NEWCOMER,
      token: invite!.properties!.email_otp,
      type: "invite",
    });
    expect(otpError).toBeNull();
    expect(session.session).not.toBeNull();

    // 4. A session exists, but the account is NOT onboarded — so a normal
    //    action is refused. This is "no access before acceptance".
    const beforeAccept = await redeeming.rpc("pglearn_rpc", {
      action: "update_me",
      payload: { display_name: "Too early" },
    });
    expect(beforeAccept.error).not.toBeNull();

    // The onboarding-exempt reads still work, which is what lets the user see
    // the invitation they are being asked to accept.
    const canRead = await redeeming.rpc("pglearn_rpc", {
      action: "get_invitation",
      payload: { invitation_id: invitationId },
    });
    expect(canRead.error).toBeNull();
    expect(canRead.data.status).toBe("pending");

    // 5. The password is set before onboarding, per spec/03's ordering.
    const { error: passwordError } = await redeeming.auth.updateUser({ password });
    expect(passwordError).toBeNull();

    await withClient(async (client) => {
      const r = await client.query("SELECT onboarded_at FROM app.profiles WHERE id=$1", [userId]);
      // Still not onboarded: setting a password is not acceptance.
      expect(r.rows[0].onboarded_at).toBeNull();
    });

    // 6. Acceptance, and only now does the account become usable.
    const accepted = await redeeming.rpc("pglearn_rpc", {
      action: "accept_invitation",
      payload: { invitation_id: invitationId },
    });
    expect(accepted.error).toBeNull();
    expect(accepted.data.status).toBe("accepted");

    const afterAccept = await redeeming.rpc("pglearn_rpc", {
      action: "update_me",
      payload: { display_name: "Newcomer" },
    });
    expect(afterAccept.error).toBeNull();

    await withClient(async (client) => {
      const r = await client.query(
        `SELECT p.onboarded_at, m.status FROM app.profiles p
           JOIN app.memberships m ON m.user_id=p.id AND m.organization_id=$2 WHERE p.id=$1`,
        [userId, ORG_A]
      );
      expect(r.rows[0].onboarded_at).not.toBeNull();
      expect(r.rows[0].status).toBe("active");
    });

    // 7. The password it chose works from a clean client.
    const signedIn = await anonClient().auth.signInWithPassword({ email: NEWCOMER, password });
    expect(signedIn.error).toBeNull();
  });
});

describe.skipIf(!hasDatabase)("AC-009 an existing verified account", () => {
  it("accepts by signing in, with no password reset", async () => {
    const invitationId = "f2000002-0000-4000-8000-000000000000";
    const testPassword = process.env.PGLEARN_TEST_PASSWORD ?? readTestPassword();

    await withClient(async (client) => {
      await client.query("DELETE FROM app.invitations WHERE user_id=$1", [DANA]);
      await client.query(
        `INSERT INTO app.invitations(id,user_id,organization_id,role,status,expires_at,created_by)
         VALUES ($1,$2,$3,'learner','pending', now() + interval '24 hours', $4)`,
        [invitationId, DANA, ORG_A, ADMIN]
      );
      await client.query("UPDATE app.profiles SET onboarded_at=NULL WHERE id=$1", [DANA]);
      await client.query(
        "UPDATE app.memberships SET status='invited' WHERE user_id=$1 AND organization_id=$2",
        [DANA, ORG_A]
      );
    });

    // Signs in with the password they already have — no reset involved.
    const client = anonClient();
    const { error: signInError } = await client.auth.signInWithPassword({
      email: "dana@example.invalid",
      password: testPassword,
    });
    expect(signInError).toBeNull();

    // Not onboarded yet, so still no access.
    const before = await client.rpc("pglearn_rpc", {
      action: "update_me",
      payload: { display_name: "Too early" },
    });
    expect(before.error).not.toBeNull();

    const accepted = await client.rpc("pglearn_rpc", {
      action: "accept_invitation",
      payload: { invitation_id: invitationId },
    });
    expect(accepted.error).toBeNull();

    const after = await client.rpc("pglearn_rpc", {
      action: "update_me",
      payload: { display_name: "Dana" },
    });
    expect(after.error).toBeNull();

    // The same password still works: acceptance did not disturb credentials.
    const again = await anonClient().auth.signInWithPassword({
      email: "dana@example.invalid",
      password: testPassword,
    });
    expect(again.error).toBeNull();
  });
});

function readTestPassword(): string {
  const file = path.join(__dirname, "../../.env.local");
  for (const raw of readFileSync(file, "utf8").split("\n")) {
    const line = raw.trim();
    if (line.startsWith("PGLEARN_TEST_PASSWORD=")) return line.split("=").slice(1).join("=").trim();
  }
  throw new Error("PGLEARN_TEST_PASSWORD is not configured");
}
